# Nixpacks configuration для Railway
# Используем только Python, игнорируем Node.js в root

[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python init_db.py"]

[start]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT run:app"
